version: "3.9"

services: 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-api:latest
    environment:
      - RUST_LOG=${RUST_LOG:-info}
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/qr.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped